# Parameters for the standard line-of-sight (LOS) controller
los_cte_delta: 5.5                        # Lookahead distance
los_cte_distance_to_max_velocity: 5.0     # Speed transition ramp distance
los_cte_max_surge_velocity: 0.5           # Highest allowed vehicle speed
los_cte_min_surge_velocity: 0.2           # Lowest allowed vehicle speed
los_cte_min_velocity_ratio: 0.1           # Slope of the velocity increase or decrease

# Parameters for the goto controller
goto_max_angle_error: 0.3                 # Maximum yaw angle error
goto_max_surge: 0.5                       # Maximum vehicle speed
goto_surge_proportional_gain: 0.4         # It converts distance to waypoint to speed

# Parameters for the anchor controller
anchor_kp: 0.1                        # Proportional term
anchor_radius: 1.0                    # Hysteresis area
anchor_min_surge: -0.1                # Minimum allowed speed
anchor_max_surge: 0.3                 # Maximum allowed speed
anchor_safety_distance: 50.0          # Maximum distance from which this controller can be used
anchor_max_angle_error: 0.5           # Maximum yaw angle error
