# WARNING!!!
# The thrusters allocation matrix "b" is defined in the code. It can not be changed using parameters.

dynamics/use_force_topic: true
#
dynamics/number_of_thrusters: 5
dynamics/number_of_fins: 0
dynamics/a_fins: 0
dynamics/k_cd_fins: 0
dynamics/k_cl_fins: 0
dynamics/max_fins_angle: 0
#
dynamics/period: 0.01
dynamics/mass: 98.0
dynamics/buoyancy: 100.0
dynamics/gravity_center: [0.0, 0.0, 0.05]
dynamics/g: 9.81
dynamics/radius: 0.4 # 0.286
#
dynamics/max_thrusters_rpm: 1200
dynamics/ctf: 0.00006835
dynamics/ctb: 0.00006835
dynamics/dzv: 0.05
dynamics/dv: 0.35
dynamics/dh: 0.4
dynamics/density: 1000.0
#
dynamics/thrusters_matrix: [-1, -1, 0, 0, 0,  0, 0, 0, 0, 1,  0, 0, -1, -1, 0,  0, 0, 0, 0, 0,  0, 0, 0.35, -0.35, 0,  -0.4, 0.4, 0, 0, 0]
#
dynamics/tensor: [8.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 8.0]
dynamics/damping: [.0, -65.0, .0, -130.0, -130.0, -130.0]
dynamics/quadratic_damping: [-148.0, -148.0, -148.0, -180.0, -180.0, -180.0]
#
#
## Meters and Rads [X, Y, Z, Roll, Pitch, Yaw]
dynamics/initial_pose: [0.0, 0.0, 0.4, 0.0, 0.0, 0.0]
dynamics/initial_velocity: [0, 0, 0, 0, 0, 0]
#
## Collisions from UWSim.
dynamics/contact_sensor_available: False
#
## WATER CURRENTs SIMULATION
dynamics/current_mean: [0.05, 0.0, 0]
dynamics/current_sigma: [0.01, 0.01, 0.01]
dynamics/current_min: [-0.1, -0.0, -0.0]
dynamics/current_max: [0.1, 0.0, 0.0]
dynamics/current_enabled: False
#
#
#
#
